// vue-front/src/components/Fetch.vue
<template>
    <div>
        <h2>Fetch</h2>
        <ul class="cards">
          <li class="card" :key="recipe._id" v-for="recipe in recipes">
              <Recipe :recipe="recipe" :graphql="false" />
          </li>
        </ul>
      </div>
</template>

<script>
import Recipe from './Recipe.vue';

export default {
  name: 'Fetch',
  data() {
    return {
      recipes: [],
    };
  },
  created: function() {
    this.fetchRecipes();
  },
  methods: {
    fetchRecipes: async function() {
      try {
        const res = await fetch('https://recipe.gareth.cool/api/recipes/');
        const recipes = await res.json();
        this.recipes = recipes;
      } catch (e) {
        /* eslint-disable-next-line */
        console.log(e);
      }
    },
  },
  components: {
    Recipe,
  },
};
</script>

<style scoped>
</style>

// react-front/src/components/Fetch.js
import React, { Component } from 'react';
import { Link } from 'react-router-dom';

export default class Fetch extends Component {
  state = {
    recipes: [],
  };

  componentWillMount = () => {
    fetch('https://recipe.gareth.cool/api/recipes/')
      .then(res => {
        return res.json();
      })
      .then(resJson => {
        this.setState({ recipes: resJson });
      });
  };

  render() {
    const { recipes } = this.state;
    return (
      <div>
        <h2>Fetch</h2>
        <ul className="cards">
          {recipes.map(recipe => {
            const { _id, name, images, dietary } = recipe;
            const { vegetarian, vegan, glutenFree } = dietary;
            return (
              <li className="card" key={name}>
                <Link to={`fetch/${_id}`}>
                  <h3>{name}</h3>
                  <div className="food-img" style={{ backgroundImage: `url(${images[0]})` }} />
                </Link>
                <div className="dietary-container">
                  <span>{vegetarian ? 'Veggie' : ''}</span>
                  <span>{vegan ? 'Vegan' : ''}</span>
                  <span>{glutenFree ? 'GF' : ''}</span>
                </div>
              </li>
            );
          })}
        </ul>
      </div>
    );
  }
}
