// vue-front/src/components/Gql.vue
<template>
    <div>
        <h2>GraphQL</h2>
        <h4 v-if="loading"><Spinner /></h4>
        <ul class="cards">
          <li class="card" :key="recipe._id" v-for="recipe in recipes">
              <Recipe :recipe="recipe" :graphql="true" />
          </li>
        </ul>
      </div>
</template>

<script>
import gql from 'graphql-tag';
import Recipe from './Recipe.vue';
import Spinner from './Spinner.vue';

const ALL_RECIPES = gql`
  query AllRecipes {
    recipes @rest(type: "Recipe", path: "") {
      _id
      name
      images
      dietary @type(name: "Dietary") {
        vegetarian
        vegan
        glutenFree
      }
    }
  }
`;

export default {
  name: 'Gql',
  apollo: {
    recipes: ALL_RECIPES,
  },
  data() {
    return {
      recipes: [],
      loading: 0,
    };
  },
  components: {
    Recipe,
    Spinner,
  },
};
</script>

<style scoped>
</style>

// react-front/src/components/Gql.js
import React, { Component } from 'react';
import { Link } from 'react-router-dom';
import { Query } from 'react-apollo';
import gql from 'graphql-tag';
import Spinner from './Spinner';

export default class Gql extends Component {
  render() {
    return (
      <Query query={ALL_RECIPES}>
        {({ data, loading }) => {
          if (loading)
            return (
              <div>
                <h2>GraphQL</h2>
                <Spinner />
              </div>
            );

          const { recipes } = data;

          return (
            <div>
              <h2>GraphQL</h2>
              <ul className="cards">
                {recipes.map(recipe => {
                  const { _id, name, images, dietary } = recipe;
                  const { vegetarian, vegan, glutenFree } = dietary;
                  return (
                    <li className="card" key={name}>
                      <Link to={`gql/${_id}`}>
                        <h3>{name}</h3>
                        <div className="food-img" style={{ backgroundImage: `url(${images[0]})` }} />
                        <div className="dietary-container">
                          <span>{vegetarian ? 'Veggie' : ''}</span>
                          <span>{vegan ? 'Vegan' : ''}</span>
                          <span>{glutenFree ? 'GF' : ''}</span>
                        </div>
                      </Link>
                    </li>
                  );
                })}
              </ul>
            </div>
          );
        }}
      </Query>
    );
  }
}

const ALL_RECIPES = gql`
  query AllRecipes {
    recipes @rest(type: "Recipe", path: "") {
      _id
      name
      images
      dietary @type(name: "Dietary") {
        vegetarian
        vegan
        glutenFree
      }
    }
  }
`;
